#pragma once

#define TEXTURE_BRAIN_COMPONENT_IN_TEXTURE_SHAPES { "5,5,1" }
#define TEXTURE_BRAIN_COMPONENT_IN_BIT_DEPTHS { 1 }
#define TEXTURE_BRAIN_COMPONENT_FILTER_SHAPES { "5,5,1" }
#define TEXTURE_BRAIN_COMPONENT_STRIDE_SHAPES { "5,5,1" }
#define TEXTURE_BRAIN_COMPONENT_OUT_BIT_DEPTHS { 110 }
